### ISSUE TITLE
Peer端无法连上Planet服务器

### ISSUE THREAD

**Issue by gundami** [sbilly/docker-zerotier-controller#2]
端口均开启，但是peer端join网络没反应，显示200 join但是网页上看不到。
同时zerotier-cli peers显示
`200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
a4de2130c2 -      PLANET    -1 RELAY`

**Comment by sbilly** [comment]
1.  peer 所在路径有对应的 planet 文件么？
2. 下面几条命令的结果都发一下

```
zerotier-cli status -j
zerotier-cli listnetworks -j
zerotier-cli listpeers -j 
``

**Comment by sbilly** [comment]
any update?

**Comment by gundami** [comment]
已经解决，在docker内建了个moon节点就好了

**Comment by qiuwei** [comment]
我也碰到同样的问题了。

@gundami 您的意思是在build的 docker里面再建一个moon 节点吗？

为什么会需要做这一步呢，我看docker容器里面已经有一个zerotier-one 实例在运行了。

**Comment by gundami** [comment]
@qiuwei zerotier-one是在运行，但是没有作为moon节点的中继功能，而这个网络是自建的所以里面没有planet节点用于让别的设备互联（我的理解），解决方法就是用idtool在docker内生成一个moon文件放进moons.d文件夹重启容器就行了

**Comment by r6c** [comment]
@gundami 请问有具体一点的步骤吗？
我这边使用以下步骤还是无法连接
```bash
bash-5.1# cd /app/config
bash-5.1# /app/ZeroTierOne/zerotier-idtool initmoon identity.public > moon.json
bash-5.1# /app/ZeroTierOne/zerotier-idtool genmoon moon.json
bash-5.1# mkdir moons.d
bash-5.1# cp *.moon moons.d/
```
后docker restart

**Comment by yinheli** [comment]
我这边也是，没有成功
