### ISSUE TITLE
国内服务器构建镜像不方便

### ISSUE THREAD

**Issue by ilay1678** [sbilly/docker-zerotier-controller#3]
源码是从github拉取的，速度非常慢；用您构建好的镜像又不能自定义planet

**Comment by sbilly** [comment]
自定义 planet 请参考：https://github.com/sbilly/docker-zerotier-controller#customize-zerotierones-controller-planets

**Comment by ilay1678** [comment]
> 自定义 planet 请参考：https://github.com/sbilly/docker-zerotier-controller#customize-zerotierones-controller-planets

我知道啊，我是说修改完还是要本地build，dockerfile里源码都是从github拉取的，国内机器很难构建成功。我只能在国外机器构建好上传镜像国内机器再拉取。遂放弃，手动搭建

**Comment by sbilly** [comment]
你可以 fork 到自己 github repo，利用 github action 来构建
